5 CLS
10 INPUT "a=";A
20 INPUT "b=";B
33  INPUT "c=";C
35 INPUT "f=";F
36 INPUT "m1=";M1
37 INPUT "m2=";M2
38 INPUT "m3=";M3
39 INPUT "G=";G
40 INPUT "S=";S
50 PRINT "(1)"
51 PRINT "       E Mz=0     m0-m1+m2-m3=0"
52 PRINT "                  m0=m1-m2+m3=120"
53 PRINT "(2)"
54 PRINT "       Mk1=m0=120                   "
55 PRINT "       Mk2=m0-m1=20                   "
56 PRINT "       Mk3=m0-m1+m2=70                   "
57 PRINT "       Mk4=m0-m1+m2-m3=0                   "
